plugins.security.ssl.transport.enabled: true
plugins.security.ssl.transport.pemcert_filepath: /usr/share/opensearch/config/certs/node.crt
plugins.security.ssl.transport.pemkey_filepath: /usr/share/opensearch/config/certs/node.key
plugins.security.ssl.transport.pemtrustedcas_filepath: /usr/share/opensearch/config/certs/ca.crt
# plugins.security.ssl.transport.enforce_hostname_verification: false

plugins.security.ssl.http.enabled: true
plugins.security.ssl.http.pemcert_filepath: /usr/share/opensearch/config/certs/node.crt
plugins.security.ssl.http.pemkey_filepath: /usr/share/opensearch/config/certs/node.key
plugins.security.ssl.http.pemtrustedcas_filepath: /usr/share/opensearch/config/certs/ca.crt
plugins.security.authcz.admin_dn:
  - "CN=admin.opensearch.local,O=TestLab,ST=VIE,C=AT"
plugins.security.nodes_dn:
  - "CN=node"
  - "CN=node1"
  - "CN=node2"
  - "CN=node3"
  - "CN=node.opensearch.local,O=TestLab,ST=VIE,C=AT"
  - "CN=node1.opensearch.local,O=TestLab,ST=VIE,C=AT"
  - "CN=node2.opensearch.local,O=TestLab,ST=VIE,C=AT"
  - "CN=node3.opensearch.local,O=TestLab,ST=VIE,C=AT"

_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    http:
      anonymous_auth_enabled: false
    authc:
      oidc_auth_domain:
        description: "Authenticate via OIDC (OpenID Connect)"
        http_enabled: true
        transport_enabled: true
        order: 2
        http_authenticator:
          type: "openid"
          challenge: true
          config:
            subject_key: "preferred_username"
            roles_key: "roles"
            openid_connect_url: "https://keycloak.opensearch.local:8443/realms/opensearch/.well-known/openid-configuration"
            client_id: "opensearch"
            client_secret: "12345678901234567890123456789012"
            openid_connect_idp.enable_ssl: true
            openid_connect_idp.verify_hostnames: true
            openid_connect_idp.pemtrustedcas_filepath: "/usr/share/opensearch/config/certs/root-ca.crt"
        authentication_backend:
          type: "noop"

      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 3
        http_authenticator:
          type: "basic"
          challenge: false
        authentication_backend:
          type: "internal"

